# Generated by Django 5.2.4 on 2025-07-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('prix', models.CharField(max_length=50)),
                ('poids', models.CharField(max_length=50)),
            ],
        ),
    ]
