# Generated by Django 5.2.4 on 2025-08-05 23:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type_promotion', models.CharField(choices=[('POURCENTAGE', 'Pourcentage'), ('MONTANT_FIXE', 'Montant fixe'), ('LIVRAISON_GRATUITE', 'Livraison gratuite')], max_length=20)),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIREE', 'Expirée'), ('SUSPENDUE', 'Suspendue')], default='ACTIVE', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('type_coupon', models.CharField(choices=[('MONTANT_FIXE', 'Montant fixe'), ('POURCENTAGE', 'Pourcentage'), ('LIVRAISON_GRATUITE', 'Livraison gratuite')], max_length=20)),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('nombre_utilisation_max', models.PositiveIntegerField(default=1, help_text="Nombre maximum d'utilisations du coupon")),
                ('nombre_utilise', models.PositiveIntegerField(default=0)),
                ('montant_minimum', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant minimum de commande pour utiliser le coupon', max_digits=10)),
                ('status', models.CharField(choices=[('ACTIF', 'Actif'), ('EXPIRE', 'Expiré'), ('SUSPENDU', 'Suspendu')], default='ACTIF', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(blank=True, help_text="Si défini, le coupon n'est utilisable que par cet utilisateur", null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='CouponCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_reduction', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('date_utilisation', models.DateTimeField(auto_now_add=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons_utilises', to='orders.commande')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisations', to='promotions.coupon')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coupon Commande',
                'verbose_name_plural': 'Coupons Commandes',
                'unique_together': {('commande', 'coupon')},
            },
        ),
        migrations.CreateModel(
            name='ProduitPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='products.produit')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='promotions.promotion')),
            ],
            options={
                'verbose_name': 'Produit Promotion',
                'verbose_name_plural': 'Produits Promotions',
                'unique_together': {('produit', 'promotion')},
            },
        ),
    ]
