# Generated by Django 5.2.4 on 2025-08-05 23:44

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_adresse', models.CharField(choices=[('LIVRAISON', 'Livraison'), ('FACTURATION', 'Facturation')], max_length=15)),
                ('nom_complet', models.CharField(max_length=200)),
                ('rue', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=20)),
                ('pays', models.CharField(default='Burkina Faso', max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('par_defaut', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adresses',
                'ordering': ['-par_defaut', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_livraison', models.CharField(choices=[('STANDARD', 'Standard (3-5 jours)'), ('EXPRESS', 'Express (1-2 jours)'), ('RETRAIT', 'Retrait en magasin')], default='STANDARD', max_length=15)),
                ('status_livraison', models.CharField(choices=[('EN_PREPARATION', 'En préparation'), ('EXPEDIE', 'Expédié'), ('EN_TRANSIT', 'En transit'), ('LIVRE', 'Livré'), ('ECHEC', 'Échec de livraison')], default='EN_PREPARATION', max_length=15)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('date_livraison_estimee', models.DateTimeField(blank=True, null=True)),
                ('date_livraison_reelle', models.DateTimeField(blank=True, null=True)),
                ('numero_suivi', models.CharField(blank=True, max_length=100)),
                ('transporteur', models.CharField(blank=True, max_length=100)),
                ('frais_livraison', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('notes_livraison', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('adresse_livraison', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livraisons', to='delivery.adresse')),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='orders.commande')),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='SuiviLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('localisation', models.CharField(blank=True, max_length=200)),
                ('date_evenement', models.DateTimeField(auto_now_add=True)),
                ('livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivi', to='delivery.livraison')),
            ],
            options={
                'verbose_name': 'Suivi Livraison',
                'verbose_name_plural': 'Suivis Livraisons',
                'ordering': ['-date_evenement'],
            },
        ),
    ]
