version: '3.8'

services:
  # Base de données MySQL
  db:
    image: mysql:8.0
    container_name: ecommerce_db
    restart: always
    environment:
      MYSQL_DATABASE: ferme-d
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: ecommerce_user
      MYSQL_PASSWORD: ecommerce_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - ecommerce_network

  # Application Django
  web:
    build: .
    container_name: ecommerce_web
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - DATABASE_NAME=ferme-d
      - DATABASE_USER=ecommerce_user
      - DATABASE_PASSWORD=ecommerce_password
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
    volumes:
      - ./media:/app/media
      - ./static:/app/static
    depends_on:
      - db
    networks:
      - ecommerce_network
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 source.wsgi:application"

  # Redis pour le cache (optionnel)
  redis:
    image: redis:7-alpine
    container_name: ecommerce_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - ecommerce_network

  # Nginx (optionnel pour la production)
  nginx:
    image: nginx:alpine
    container_name: ecommerce_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./media:/app/media
      - ./static:/app/static
    depends_on:
      - web
    networks:
      - ecommerce_network

volumes:
  mysql_data:

networks:
  ecommerce_network:
    driver: bridge